---
- hosts: web
  become: yes
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
        name: nginx
        state: started
    - name: copy the nginx config file and restart nginx
      copy:
        src: ./Webservers/hello-world
        dest: /var/www/html/index.nginx-debian.html
    - name: restart nginx
      service:
        name: nginx
        state: restarted
- hosts: loadbalancer
  become: yes
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
        name: nginx
        state: started
    - name: copy the nginx config file and restart nginx
      copy:
        src: ./LoadBalancer/loadbalancerconfig
        dest: /etc/nginx/sites-available/default
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    -name: copy sudoers file into sudoers.d
     copy:
      src: ./LoadBalancer/sudoers
      dest: /etc/sudoers.d/overrides
- hosts: testclient1
  become: yes
  tasks:
    - name: copy the loadbalancer healthcheck script and run
      copy:
        src: ./testclient/lb_healthcheck
        dest: /home/vagrant/
    - name: run load balancer healthcheck
      script: /home/vagrant/lb_healtcheck
